### ISSUE TITLE
Broadway producer & consumer

### ISSUE THREAD

**Issue by mkaput** [mmmries/jetstream#31]
- Reference: https://hexdocs.pm/broadway/custom-producers.html
- Module: `OffBroadway.Jetstream`
- Try to extract shared parts with PullConsumer API into what I would like to call a Low-Level API. See #8.
- I wouldn't create a separate library for this. Instead, I would use [soft-dependencies pattern](https://nts.strzibny.name/soft-dependencies-in-elixir-projects/) and write the code in this library.

**Comment by sswrk** [comment]
Hi @brandynbennett, 

We already asked Michael and we'd like to know opinion too: are you OK with including the Jetstream Broadway producer in this library? Thanks.

**Comment by brandynbennett** [comment]
@sswrk I think that makes sense so long as Broadway is a soft-dependency and is opt-in as mentioned above.
