### ISSUE TITLE
Support early connection versions?

### ISSUE THREAD

**Issue by mmmries** [mmmries/jetstream#35]
As i was testing this with some of my work projects I ran into a case where I have a project that is using `{:connection, "~> 1.0"}` in it's deps. I think the 1.0.X releases are still pretty common out in the community. Are we depending on behavior changes that happened between 1.0 and 1.1?

I took a quick look, but didn't feel confident that we were using 1.1 specific things from that library

**Comment by mmmries** [comment]
It looks like this was introduced by @sswrk in #17 so that's probably the best person to weigh in on whether we need 1.1 or if we are okay specifying `1.0` as our dependency?

**Comment by mkaput** [comment]
I have diffed `connection` `v1.1.0` vs `v1.0.4` and the only difference was removing warnings on newer Elixir versions, so this library should work with `connection` `v1.0.x`.

Note though that this library requires Elixir `~> 1.10` which is already higher than `connection` `v1.1.x` requirement (`~> 1.7`), so `mix` will automatically bump locked version of `connection` to `v1.1.x` **always**.
