### ISSUE TITLE
Invalid PullConsumers should log errors or crash?

### ISSUE THREAD

**Issue by mmmries** [mmmries/jetstream#36]
While doing some testing today, I found that if I started up a `PullConsumer` that specified a stream name and consumer name that didn't actually exist, it would boot just fine, but would never actually do any work.

## Quick Reproducible

* start up a fresh jetstream server with no streams/consumers
* in IEx run the `setup.exs` the script below
  * I think we should either log an error message at this point, or crash the `PullConsumer`
* Now run the `setup_consumer.exs` script, this creates the stream + consumer and publishes a few messages
  * If the PullConsumer is still running at this point, I think it should start receiving these messages

```elixir setup.exs
defmodule MyConsumer do
  use Jetstream.PullConsumer

  def start_link(nil) do
    Jetstream.PullConsumer.start_link(__MODULE__, nil)
  end

  @impl Jetstream.PullConsumer
  def init(nil) do
    consumer = [
      connection_name: :gnat,
      stream_name: "my_stream",
      consumer_name: "my_stream"
    ]
    {:ok, nil, consumer}
  end

  @impl Jetstream.PullConsumer
  def handle_message(message, state) do
    IO.inspect(message, label: "message")
    {:ack, state}
  end
end

config = %{
  name: :gnat,
  backoff_period: 4_000,
  connection_settings: [%{host: "127.0.0.1", port: 4222}]
}

{:ok, _pid} = Gnat.ConnectionSupervisor.start_link(config)

{:ok, pid} = MyConsumer.start_link(nil)
```

```elixir setup_consumer.exs
stream = %Jetstream.API.Stream{
  discard: :old,
  name: "my_stream",
  num_replicas: 1,
  storage: :file,
  subjects: ["foo"]
}

Jetstream.API.Stream.create(:gnat, stream)

consumer = %Jetstream.API.Consumer{stream_name: "my_stream", durable_name: "my_stream"}

Jetstream.API.Consumer.create(:gnat, consumer)

Enum.each(1..10, fn(i) ->
  Gnat.pub(:gnat, "foo", Jason.encode!(%{foo: "bar", counter: i}))
end)
```

**Comment by mkaput** [comment]
I have checked out what Go client does and it simply asks NATS if stream exists: https://github.dev/nats-io/nats.go/blob/5753a5f29250b05ca3b668015ecf404fd00ccf02/js.go#L1388-L1396

Good catch! We should also do this. I think the relevant code should be placed in `connect` callback implementation.
