### ISSUE TITLE
Test "Jetstream.PullConsumer allows setting custom inbox prefix" (Jetstream.PullConsumer.ConnectivityTest) is wonky

### ISSUE THREAD

**Issue by mkaput** [mmmries/jetstream#37]
https://github.com/mmmries/jetstream/runs/5688498005?check_suite_focus=true

**Comment by mmmries** [comment]
🤔 Maybe jetstream wasn't full up and running by that time? Or we could try a slightly longer timeout on the `assert_receive`?

**Comment by mkaput** [comment]
@mmmries possibly

@sswrk could you please take a look at this when you'll have spare cycles? 🙂 

This is a low priority issue. So far, we only have encountered this case **once**.
