### ISSUE TITLE
Validate Stream Name / Consumer Name?

### ISSUE THREAD

**Issue by mmmries** [mmmries/jetstream#38]
Jetstream specifies a few requirements for stream and consumer names: https://docs.nats.io/running-a-nats-service/nats_admin/jetstream_admin/naming

I wasn't aware of these at first and when I tried to create a stream with a name like `"stream.test"` and rather than getting back an error message I got back an `{:error, :timeout}` return. I would have expected the jetstream server to reply with an error message, but it seems like it just didn't respond at all?

This isn't high priority issue, but I wanted to log it as something that maybe we should validate within our library to give the user a more helpful error message in the future.

**Comment by mkaput** [comment]
Oh, that's surprising behaviour. I didn't expect that.

I have checked out what NATS Golang client does and indeed they do some client-side validation. https://github.dev/nats-io/nats.go/blob/5753a5f29250b05ca3b668015ecf404fd00ccf02/jsm.go#L567-L574

**Comment by brandynbennett** [comment]
@mmmries Should this be closed?

**Comment by mmmries** [comment]
Yep, good all @brandynbennett
