### ISSUE TITLE
Production Readiness

### ISSUE THREAD

**Issue by MarceColl** [mmmries/jetstream#70]
Hello, good morning/afternoon/night!

With our company we have a currently deployed NATS setup that we are about to upgrade so we are able to use Jetstream. We have part of the stack in Elixir and yours is the only implementation we've found so far. How would you rate the production readiness of your client atm? I see the current version is 0.0.5, which if following semver is a bit scary to use in a production setting. But I thought best to first talk with you to see what are your thoughts on that.

Thanks in advance!

**Comment by mmmries** [comment]
Hi @MarceColl 👋 

The best person to answer your questions is @brandynbennett who has been actively working on this project to get it ready for use in our production systems at Spiff. I would summarize my own feelings like this:

* This library is not "battle-tested" or "production proven" at this point
* It is being designed and worked on with the intent of being used at-scale in a production environment with SLAs and is expected to be a very resilient part of our infrastructure
* I would be happy to roll it out in a beta-usage within our own production systems, but would keep a close eye on it

I hope that helps to give you some context on the current status of the project and hopefully Brandyn will have time to weigh in as well

**Comment by mmmries** [comment]
I hope that answers your question @MarceColl . We would love to get your feedback, or feedback from your team, if you choose to make use of this library, but I understand that adopting an early stage library involves risk and work. If your team settles on another approach that is totally understandable.

I'll close this issue for now and we'll try to update the README as the library becomes more mature

**Comment by MarceColl** [comment]
Hello, sorry for the delay in responding.

That does answer my question, we will evaluate internally based on this. Thanks for the thorough responses :)
