### ISSUE TITLE
Simple PullConsumer API MVP

### ISSUE THREAD

**Issue by mkaput** [mmmries/jetstream#8]
Let's start with trying to make the `PullConsumer` module usable by end-users and see how far could we go with the following API design, no matter what is happening under the hood (i.e. do whatever is fastest to implement).

I imagine we may eventually expose 2/3 APIs in this library, each meeting a particular use-case:

1. **Simple Pull Consumer API**, which basically would require end users to write a GenServer-style module and start it within their supervision trees. It would automatically talk with Gnat connection specified by connection name.
2. **NATS Jetstream Broadway Producer** (may end up in separate `broadway_jetstream` package), which would implement pull consuming on to of GenStage. GenStage handles demands and acknowledges in its own way, so this API probably won't be possible to be implemented on top of Simple Pull Consumer API.
3. **Low-level API**, which would consist of building blocks needed for our higher-level APIs. I am keen to make this API public. It will probably look like a set of:
   - dedicated pub/sub operations
   - the `ack` functions will be part of it
   - it would expose something like the `NextMsg` function from Go client library: https://github.com/nats-io/jsm.go#consuming

## Simple Pull consumer API

Let's focus on the Pull Consumer module a behaviour. Here goes example usage:

```elixir
defmodule MyApp.Application do
  use Application

  @impl true
  def start(_type, _args) do
    children = [
       # Create NATS connection
       {Gnat.ConnectionSupervisor, ...},
       # Start NATS Jetstream Pull Consumer
       {MyApp.PullConsumer,
        %{
          connection_name: :gnat,
          stream_name: "TEST",
          consumer_name: "TEST"
        }}
     ]
    opts = [strategy: :one_for_one]
    Supervisor.start_link(children, opts)
  end
end

defmodule MyApp.PullConsumer do
  use Jetstream.PullConsumer

  def handle_message(topic, message) do
    # Do some processing with the message.
    :ack
  end
end

defmodule Jetstream.PullConsumer do
  @callback handle_message(topic :: String.t(), message :: Gnat.message()) :: :ack | :nack | :noreply
end
```

1. Depending on the return value from handle_message, we will automatically send `+NXT`, `-NAK` replies, or do nothing (this case requires verification whether it makes any sense).
2. In the future we may introduce another action: `:async`, which would kinda work like `:noreply`, but the user promises that they will manually call `ack` etc. functions.

## Don't bother with:
1. Message ordering. `Gnat.ConsumerSupervisor` doesn't bother, so we would probably have to fix that beforehand.
2. Failure recovery. Let everything crash and restart from ground up.
3. Batching & Demands, just pull messages one by one
4. GenServer-style PullConsumer state, let's assume it will be stateless as for now (so, no `state` argument in callbacks).
5. GenServer-style `handle_info` callback 

cc @mmmries @marmor157 @byu

**Comment by mkaput** [comment]
Edit: Added `topic` argument.

**Comment by byu** [comment]
Not to get too pedantic, and while I do see that `subject` and `topic` are used often interchangeably, but I believe that NATS uses 'subject-based messaging', not `topics`. 

That is, a `topic` is a [named logical channel (an entity)](https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern) to which messages are published and subscribed.  RabbitMQ exposes this capacity through ["Topic Exchanges"](https://www.erlang-solutions.com/blog/rabbits-anatomy-understanding-topic-exchanges/) that would act as that logical entity-channel, which receives and route messages based on the `routing key` (which is more like a NATS `subject`). Similarly, a [topic in Kafka](https://data-flair.training/blogs/kafka-topic-architecture/) is a modeled as a "logical stream" of partitioned messages.

For example, in a topic based system for Kafka or RabbitMQ, an "ORDERS" topic could receive all CRUD messages for orders in the system.

Although, a specific instance of a subject (e.g. `orders`) MAY be domain modeled as the equivalent single topic (e.g. `orders`) in core NATS, it would likely be more common that a large subject hierarchy (e.g the subject-with-wildcard "orders.>") is used to represent a topic (i.e. a logical concept)... And for core NATS, topics are unspecified, and inferred from actual publisher published messages and subscriber subscribed subjects (via code and usage). For example,  a subject of `orders.created` and `orders.canceled` could all be subjects for a topic regarding orders.

To project this idea onto Jetstream, we could think of the Stream as the `topic`, identified  the "Stream Name", which is a made up of messages from a set of defined subjects (akin to rabbitmq routing key).

So in the above API endpoint, the `handle_message` it would be more proper to use `subject` for the actual message received.

I do see `topic` used everywhere in the nats.ex library, so I think I see where this name for the argument came from... But I think it's something that we may want to distinguish when handling actual messages with explicit subjects.

**Comment by byu** [comment]
I don't have an opinion on the reuse of `Gnat.message()` vs `Jetstream.message()` , or any thoughts about possible advantages or disadvantages .

**Comment by mkaput** [comment]
Now I think we should introduce own type in order to separate Jetstream API from Gnat API.
